import {
  RiCloseLine,
  RiFlagLine,
  RiHome2Line,
  RiRefreshLine,
  RiInformationLine,
  RiAddCircleLine,
  RiEyeLine,
  RiLink,
  RiDeleteBinLine,
  RiArrowRightLine,
  RiSearchLine,
  RiSaveLine,
  RiShieldCheckLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiEditLine,
} from "oh-vue-icons/icons"

export const icons = [
  RiCloseLine,
  RiFlagLine,
  RiHome2Line,
  RiRefreshLine,
  RiInformationLine,
  RiAddCircleLine,
  RiEyeLine,
  RiLink,
  RiDeleteBinLine,
  RiArrowRightLine,
  RiSearchLine,
  RiSaveLine,
  RiShieldCheckLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiEditLine,
]
