import {
  RiCloseLine,
  RiFlagLine,
  RiHome2Line,
  RiRefreshLine,
  RiInformationLine,
  RiAddCircleLine,
  RiEyeLine,
  RiLink,
  RiDeleteBinLine,
  RiArrowRightLine,
  RiSearchLine,
  RiSaveLine,
  RiShieldCheckLine,
} from "oh-vue-icons/icons/ri"

export const icons = [
  RiCloseLine,
  RiFlagLine,
  RiHome2Line,
  RiRefreshLine,
  RiInformationLine,
  RiAddCircleLine,
  RiEyeLine,
  RiLink,
  RiDeleteBinLine,
  RiArrowRightLine,
  RiSearchLine,
  RiSaveLine,
  RiShieldCheckLine,
]
