export const stateLabel = {
  public: "Public",
  private: "Privé",
  draft: "Brouillon",
  restricted: "Restreint",
}
export const evaluationGrades: Record<number, string> = {
  4: "Très abouti",
  3: "Abouti",
  2: "Moyennement abouti",
  1: "Peu abouti",
  0: "Pas abouti",
}
export const evaluationColors: Record<number, string> = {
  4: "#00A95F",
  3: "#85D04A",
  2: "#FBE769",
  1: "#FCCB86",
  0: "#F99389",
}
export const RECOMMENDATION_CRITERION = "recommendation"
export const COLORS_PER_GRADE: Record<string, string> = {
  "0": "#F99389",
  "1": "#FCCB86",
  "2": "#FBE769",
  "3": "#85D04A",
  "4": "#00A95F",
}
export const fileExtensionToMediaType: Record<string, string> = {
  ".aac": "audio",
  ".arc": "archive",
  ".avi": "video",
  ".azw": "ebook",
  ".bmp": "image",
  ".bz": "archive",
  ".bz2": "archive",
  ".csh": "code",
  ".css": "code",
  ".csv": "tableur",
  ".doc": "document",
  ".docx": "document",
  ".epub": "ebook",
  ".gif": "image",
  ".htm": "code",
  ".html": "code",
  ".ico": "image",
  ".jpeg": "image",
  ".jpg": "image",
  ".json": "texte",
  ".mid .midi": "audio",
  ".mpeg": "video",
  ".odp": "presentation",
  ".ods": "tableur",
  ".odt": "document",
  ".oga": "audio",
  ".ogv": "video",
  ".png": "image",
  ".pdf": "pdf",
  ".ppt": "presentation",
  ".pptx": "presentation",
  ".rar": "archive",
  ".rtf": "texte",
  ".sh": "code",
  ".svg": "image",
  ".tar": "archive",
  ".tiff": "image",
  ".tif": "image",
  ".ts": "code",
  ".wav": "audio",
  ".weba": "audio",
  ".webm": "video",
  ".webp": "image",
  ".xhtml": "code",
  ".xls": "tableur",
  ".xlsx": "tableur",
  ".xml": "code",
  ".zip": "archive",
  ".3gp": "video",
  ".3g2": "archive",
}
export const mediaTypeToSvgPath: Record<string, string> = {
  audio: "/icons/media/music2-line.svg",
  archive: "/icons/business/archive-line.svg",
  video: "/icons/media/film-line.svg",
  ebook: "/icons/document/book-2-line.svg",
  image: "/icons/meida/image-line.svg",
  code: "/icons/development/code-box-line.svg",
  tableur: "remix:ri-table-line",
  document: "/icons/document/file-text-line.svg",
  texte: "remix:ri-text-line",
  presentation: "remix:ri-slideshow-3-line",
  pdf: "/icons/document/file-pdf-line.svg",
}
